<div class="container" style="margin-top:10px;">
	<div class="jumbotron">
		<h1><?=$this->translate('hello');?>, ZF3!</h1>
		<p>...</p>
		<p><a class="btn btn-primary btn-lg" href="<?=$this->lang;?>/test1/4/" role="button"><?='TEST 1';?></a></p>
		<p><a class="btn btn-primary btn-lg" href="<?=$this->lang;?>/test2/" role="button"><?='TEST 2';?></a></p>
		<p><a class="btn btn-primary btn-lg" href="<?=$this->lang;?>/test3/" role="button"><?='TEST 3';?></a></p>
	</div>
</div>